Development 100 package security portal
criticalmanufacturing/cli pull request #115
Opened 2022-01-27 18:17 UTC by jrk94

closes #100

2022-01-27 18:32 UTC, m-s- submitted a review, later dismissed

2022-01-27 18:32 UTC, m-s- commented on cmf-cli/cmf.csproj
> +    <None Remove="resources\templateFiles\SecurityPortal\config.json" />
we should have a single entry in csproj for templateFiles

2022-01-27 18:32 UTC, m-s- commented on tests/Utilities/TestUtilities.cs
> +    /// <summary>
please comment your public methods :)

2022-02-10 18:12 UTC, joaoopereira submitted a review, later dismissed

2022-02-10 18:12 UTC, joaoopereira commented on cmf-cli/resources/template_feed/securityPortal/SecurityPortal.Package/cmfpackage.json
> +  "<keywords>cmf-root-package</keywords>": null,
is this correct?

2022-03-24 15:39 UTC, m-s- requested changes

2022-03-24 15:39 UTC, m-s- commented on cmf-cli/resources/template_feed/securityPortal/.template.config/template.json
> +    "idSegment": {
seems to me you don't need these next 2 symbols

2022-03-24 15:51 UTC, joaoopereira requested changes

2022-03-24 15:51 UTC, joaoopereira commented on cmf-cli/Handlers/SecurityPortalPackageTypeHandler.cs
> +                    "/app",
this will not work for traditional installations

2022-03-24 15:51 UTC, joaoopereira commented on cmf-cli/Handlers/SecurityPortalPackageTypeHandler.cs
> +            };
not neeeded I think

2022-03-25 18:10 UTC, joaoopereira approved these changes

2022-03-25 18:15 UTC, merged