Development add support for io t repository packages
criticalmanufacturing/cli pull request #152
Opened 2022-03-15 18:13 UTC by joaoopereira

2022-03-15 18:20 UTC, joaoopereira commented on cmf-cli/Handlers/PackageType/IoTRepositoryHandler.cs
> +                //targetDirectory:
remove commented code

2022-03-15 18:20 UTC, joaoopereira commented on cmf-cli/Handlers/PackageType/IoTRepositoryHandler.cs
> +        public override void Pack(IDirectoryInfo packageOutputDir, IDirectoryInfo outputDir)
duplicated code

2022-03-16 10:34 UTC, m-s- requested changes

2022-03-16 10:34 UTC, m-s- commented on cmf-cli/Handlers/PackageType/IoTRepositoryHandler.cs
> +    ///
please fill in the comments...

2022-03-16 10:34 UTC, m-s- commented on cmf-cli/Objects/Step.cs
> +        [JsonProperty(Order = 12)]
what are these 2 for?

2022-03-21 10:37 UTC, joaoopereira commented
this PR should not be closed until Cloud team fixes this issue.

2022-04-13 11:22 UTC, closed without merging

2022-04-13 11:41 UTC, m-s- commented
This was superseeded by new DF steps available in 8.3.5.