feat(pipelines)!: support package installation by environment
criticalmanufacturing/cli pull request #172
Opened 2022-04-21 09:17 UTC by joaoopereira

2022-04-26 14:58 UTC, m-s- commented
Please detail a migration path for the breaking change in a doc PR or a changelog entry (this can be done via the body of the commit message, it will automatically be appended in the change log)

2022-04-27 08:24 UTC, m-s- requested changes

2022-04-27 08:24 UTC, m-s- commented on cmf-cli/resources/template_feed/init/Builds/CD-Containers.yml
> +              $PackageId = "${{ variables.RootPackageIdToInstall }}"
I'd love a fallback here for "Cmf.Custom.Package" for backwards compatibility

2022-04-28 14:41 UTC, joaoopereira commented
> Please detail a migration path for the breaking change in a doc PR or a changelog entry (this can be done via the body of the commit message, it will automatically be appended in the change log)

code refactored to avoid migration path

2022-04-28 17:23 UTC, m-s- approved these changes

2022-04-29 14:12 UTC, merged