fix(init): clean each Release pipeline stage so that multiple loads work correctly
criticalmanufacturing/cli pull request #208
Opened 2022-08-25 08:01 UTC by m-s-

2022-08-25 08:03 UTC, m-s- commented
@cesarmeira90 can you also chime in on this as this was originally your analysis?

2022-09-13 13:22 UTC, joaoopereira requested changes

2022-12-19 17:24 UTC, m-s- commented
@cesarmeira90 @joaoopereira can you confirm this is to be abandoned? I'm under the impression the important gist of this PR was meanwhile implemented in other PRs

2022-12-21 16:34 UTC, joaoopereira commented
@m-s- yes, it can be abandoned. we also have a new ci-release coming, so this PR doesn't make sense anymore

2023-02-07 11:13 UTC, closed without merging