pipelines cleanup and new CD-Containers
criticalmanufacturing/cli pull request #93
Opened 2022-01-04 13:44 UTC by joaoopereira

2022-01-04 19:57 UTC, m-s- requested changes

2022-01-05 11:30 UTC, joaoopereira commented on cmf-cli/resources/template_feed/init/Builds/CI-Publish.yml
> -# BackupRestoreTools Artifact
correct. we still need the tool to backup and restore

2022-01-05 11:31 UTC, joaoopereira commented on cmf-cli/resources/template_feed/init/Builds/CD-Containers.yml
> +              $addrPackageSourceShare = (($packageSourceShare -split "\\" | Where {  $_ -ne ""  })[0] -replace ".cmf.criticalmanufacturing.com")
I think this is no longer needed with NFS

2022-01-05 12:03 UTC, m-s- approved these changes

2022-01-05 12:04 UTC, merged